### PR TITLE
Please test the docker config 

### PR DESCRIPTION
**Pull request by evfairchild**
This will let us run the api individually without pointing to each others computers over VPN.  We can also hold off on running the API on dedicated hardware until we are further along. Please test this on your end.  Pull the docker branch and follow the amended READMe in master.

### CODE REVIEW

**Comment by csuttner** [comment]
Awesome, looking forward to prototyping with a local docker container. Will check this out tonight and let you know how it goes.

**Comment by csuttner** [comment]
Works great. Approved.

**Comment by csuttner** [comment]
Was able to get this to work but had to change application transport security settings to allow arbitrary uploads. We'll probably want to revert this once we move away from local machine API testing and have a secure cloud connection etc.

**Comment by evfairchild** [comment]
i'll look into SSL for the flask api.  hopefully its easy cuz im not super thrilled by security stuff

**Pull request merged**
